### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by cozmo14047** [ThomAce/OnnxStreamGui#1]
hi i set this up and when i start it it is always showing 0% is this a glitch is it actully doing anything,
if you have any ideas please let me know thanks

**Comment by ThomAce** [comment]
Hi, which GUI is the subject? Web or desktop one?
The web version is still in alpha stage.
The GUI is in beta stage, pre-release stage.

Both of them currently working at this stage with OnnxStreamPlus. (I submitted a pull request to OnnxStream to implement the custom seed function)

Please provide some evidence photos what you are using and how you configured and what you can see.

**Comment by cozmo14047** [comment]
Hi there thanks for your reply.
im unabout the desktop one as i could never find how to install the web one. my problem is on my pi 3 i start it to create a photo at the top it says 0% and that never moves and im not sure if its actully doing anything. if you need photo ill get some later.
many thanks

**Comment by cozmo14047** [comment]
I figured it it was because it didn't build the actual ai which takes hours
